owner: six-star-connect
repo: status-monitor

sites:
  - name: Manage
    url: $manage_URL
  - name: API
    url: $api_URL
  - name: N8N
    url: $n8n_URL
  - name: Six Star Global
    url: $global_URL
  - name: ITGlue
    url: $itglue_URL
  - name: 3CX
    url: $phones_url
   

status-website:
  baseUrl: /status-monitor
  logoUrl: https://raw.githubusercontent.com/six-star-connect/status-monitor/master/assets/assets/upptime-icon.svg
  favicon: https://raw.githubusercontent.com/six-star-connect/status-monitor/master/assets/assets/favicon.ico
  name: Six Star Status Monitor
  introTitle: "**Six Star** Status Monitor keeps you updated with real-time service performance and availability."
  introMessage: Welcome to the Six Star Status Monitor, your go-to platform for up-to-the-minute updates on the status and reliability of our services. Our system provides live data, ensuring you're always in the know about any service interruptions or maintenance schedules. Stay informed and confident with Six Star's top-tier performance monitoring.
  theme: light
  css: "footer { display: none !important }"
  navbar:
    - title: Status
      href: /status-monitor
    - title: Manage
      href: https://manage.sixstar.support
    - title: Six Star Global
      href: https://sixstar.global
