# Change these first
owner: six-star-connect # Your GitHub organization or username, where this repository lives
repo: status-monitor # The name of this repository

sites:
  - name: Manage
    url: https://manage.sixstar.support
  - name: API
    url: https://api.sixstar.click
  - name: N8N
    url: https://n8n.sixstar.click
  - name: Six Star Global
    url: https://sixstar.global
  - name: ITGlue
    url: https://six-star.eu.itglue.com
  - name: 3CX
    url: https://sixstar.3cx.uk:5001
   

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sixstar.support
  # baseUrl: /status-monitor
  logoUrl: https://raw.githubusercontent.com/six-star-connect/status-monitor/master/assets/assets/upptime-icon.svg
  favicon: https://raw.githubusercontent.com/six-star-connect/status-monitor/master/assets/assets/favicon.ico
  name: Six Star Status Monitor
  introTitle: "**Six Star** Status Monitor keeps you updated with real-time service performance and availability."
  introMessage: Welcome to the Six Star Status Monitor, your go-to platform for up-to-the-minute updates on the status and reliability of our services. Our system provides live data, ensuring you're always in the know about any service interruptions or maintenance schedules. Stay informed and confident with Six Star's top-tier performance monitoring.
  navbar:
    - title: Status
      href: /
    - title: Manage
      href: https://manage.sixstar.support
    - title: Six Star Global
      href: https://sixstar.global

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
